from datetime import datetime, timezone
import logging
 feature/frontend-scaffold
import os

from fastapi import APIRouter, Depends, HTTPException, UploadFile, File
from fastapi.responses import Response

from app.api.auth_routes import get_current_user
from app.database.asset_repository import create_asset
from app.database.defect_repository import replace_analysis_for_inspection


from fastapi import APIRouter, Depends, HTTPException, UploadFile, File, Form

from app.schemas.inspection_schema import InspectionOut
from app.schemas.defect_schema import AnalysisOut

from app.api.auth_routes import get_current_user

from app.services.file_storage import save_uploaded_image
from app.services.image_quality import assess_image_quality

from app.services.severity_engine import calculate_severity
from app.services.risk_engine import calculate_risk, risk_explanation

 main
from app.database.inspection_repository import (
    create_inspection,
    get_inspection_by_id,
    get_inspections_by_asset,
    update_inspection,
)
 feature/frontend-scaffold
from app.schemas.defect_schema import AnalysisOut
from app.schemas.inspection_schema import InspectionOut
from app.services.image_quality import assess_image_quality
from app.services.mongo_image_storage import (
    store_image,
    get_image,
    create_temp_image_file,
)
from app.services.severity_engine import calculate_severity
from app.services.risk_engine import calculate_risk, risk_explanation
from app.ai.defect_detection import detect_defects


from app.database.asset_repository import get_asset_by_id

from app.database.defect_repository import (
    replace_analysis_for_inspection,
)

# CHANGE THIS IMPORT TO YOUR ACTUAL YOLO SERVICE
# from app.services.yolo_service import run_defect_detection


logger = logging.getLogger(__name__)
 main

router = APIRouter(tags=["inspections"])

logger = logging.getLogger(__name__)

SEVERITY_ORDER = {
    "minor": 1,
    "moderate": 2,
    "serious": 3,
    "critical": 4,
}


def _to_inspection_out(doc: dict) -> InspectionOut:
    return InspectionOut(
        id=str(doc["_id"]),
        inspectionId=doc.get("inspectionId", ""),
        assetId=doc.get("assetId", ""),
        userId=doc.get("userId", ""),
        imageUrl=doc.get("imageUrl", ""),
        inspectionDate=doc.get(
            "inspectionDate",
            datetime.now(timezone.utc),
        ),
        status=doc.get("status", "uploaded"),
        imageQuality=doc.get("imageQuality"),
        analysisStatus=doc.get("analysisStatus"),
        severity=doc.get("severity"),
        risk=doc.get("risk"),
        modelVersion=doc.get("modelVersion"),
        analyzedAt=doc.get("analyzedAt"),
    )


 feature/frontend-scaffold
@router.post("/api/inspections/upload-image")
=======
# ============================================================
# UPLOAD INSPECTION IMAGE
# ============================================================

@router.post(
    "/api/inspections/upload",
    response_model=InspectionOut,
    status_code=201,
)
 main
async def upload_inspection_image(
    file: UploadFile = File(...),
    current_user: dict = Depends(get_current_user),
):
 feature/frontend-scaffold
    """
    Step 1 of the inspection workflow.

    The user uploads an image before an asset exists.
    The image is stored in MongoDB and receives a temporary upload ID.
    """

    image_id = await store_image(file)

    from app.database.connection import db

    await db.inspectionImages.update_one(
        {"imageId": image_id},
        {
            "$set": {
                "userId": str(current_user["_id"]),
                "status": "pending",
            }
        },
    )

    image = await get_image(image_id)

    return {
        "uploadId": image_id,
        "filename": image.get("filename") if image else file.filename,
        "contentType": image.get("contentType")
        if image
        else file.content_type,
        "size": image.get("size") if image else None,
        "status": "uploaded",
    }


@router.post(
    "/api/inspections/create",
    response_model=InspectionOut,
    status_code=201,
)
async def create_inspection_from_upload(
    upload_id: str,
    name: str,
    type: str,
    location: str,
    description: str | None = None,
    inspection_date: datetime | None = None,
    deterioration_status: str | None = None,
    current_user: dict = Depends(get_current_user),
):
    """
    Step 2 of the inspection workflow.

    The uploaded image is now attached to the newly-created asset
    and inspection. The Asset ID is generated by the backend here.
    """

    from app.database.connection import db

    image = await get_image(upload_id)

    if image is None:
        raise HTTPException(
            status_code=404,
            detail="Uploaded image not found.",
        )

    if str(image.get("userId", "")) != str(current_user["_id"]):
        raise HTTPException(
            status_code=404,
            detail="Uploaded image not found.",
        )

    if image.get("status") != "pending":
        raise HTTPException(
            status_code=400,
            detail="This uploaded image has already been used.",
        )

    # Generate the Asset ID only now, after the user has supplied
    # the asset details.
    asset_data = {
        "name": name,
        "type": type,
        "description": description,
        "location": location,
    }

    asset = await create_asset(asset_data)
    asset_id = asset["assetId"]

    inspection_date = inspection_date or datetime.now(timezone.utc)

    asset = await get_asset_by_id(asset_id)

    if asset is None:
        raise HTTPException(
            status_code=404,
            detail="Asset not found",
        )

    image_url = await save_uploaded_image(
        file,
        asset_id,
 main

    inspection_data = {
        "assetId": asset_id,
        "userId": str(current_user["_id"]),
        "imageId": upload_id,
        "imageUrl": f"/api/inspections/image/{upload_id}",
        "inspectionDate": inspection_date,
        "status": "uploaded",
        "analysisStatus": "pending",
    }

 feature/frontend-scaffold
    if deterioration_status:
        inspection_data["deteriorationStatus"] = deterioration_status

    created = await create_inspection(inspection_data)

    await db.inspectionImages.update_one(
        {"imageId": upload_id},
        {
            "$set": {
                "status": "attached",
                "assetId": asset_id,
                "inspectionId": created["inspectionId"],
            }
        },

    created = await create_inspection(
        inspection_data
 main
    )

    return _to_inspection_out(created)


 feature/frontend-scaffold
@router.get("/api/inspections/image/{image_id}")
async def get_inspection_image(
    image_id: str,
    current_user: dict = Depends(get_current_user),
):
    """
    Return an image stored in MongoDB.

    The endpoint is authenticated so inspection images are not public.
    """

    image = await get_image(image_id)

    if image is None:
        raise HTTPException(
            status_code=404,
            detail="Image not found.",
        )

    if str(image.get("userId", "")) != str(current_user["_id"]):
        raise HTTPException(
            status_code=404,
            detail="Image not found.",
        )

    return Response(
        content=image["data"],
        media_type=image.get(
            "contentType",
            "application/octet-stream",
        ),
    )


@router.post(
    "/api/inspections/{inspection_id}/analyze",
    response_model=AnalysisOut,
)
async def analyze_inspection(
    inspection_id: str,
    current_user: dict = Depends(get_current_user),
):
    """
    Run the real image-quality -> YOLO -> severity -> risk pipeline.
    """

    inspection = await get_inspection_by_id(inspection_id)

    if inspection is None:
        raise HTTPException(
            status_code=404,
            detail="Inspection not found.",
        )

    if str(inspection.get("userId", "")) != str(current_user["_id"]):
        raise HTTPException(
            status_code=404,
            detail="Inspection not found.",
        )

    image_id = inspection.get("imageId")

    if not image_id:
        raise HTTPException(
            status_code=400,
            detail="Inspection has no stored image.",
        )

    temp_path = None

    try:
        temp_path = await create_temp_image_file(image_id)

        # =========================================================
        # 1. IMAGE QUALITY
        # =========================================================

        quality = assess_image_quality(temp_path)

        # Persist image quality immediately so the inspection
        # contains the result even before the remaining analysis
        # stages finish.
        await update_inspection(
            inspection_id,
            {
                "imageQuality": quality,
                "analysisStatus": "processing",
                "updatedAt": datetime.now(timezone.utc),
            },
        )

        # =========================================================
        # 2. REAL YOLO DEFECT DETECTION
        # =========================================================

        detections = detect_defects(temp_path)

        defects = []

        # =========================================================
        # 3. SEVERITY FOR EVERY DETECTED DEFECT
        # =========================================================

        for detection in detections:
            defect_type = detection.get(
                "defectType",
                detection.get("class", "unknown"),
            )

            confidence = float(
                detection.get("confidence", 0)
            )

            bounding_box = detection.get(
                "boundingBox",
                detection.get("bbox"),
            )

            if not bounding_box:
                continue

            severity = calculate_severity(
                defect_type=defect_type,
                confidence=confidence,
                bounding_box=bounding_box,
            )

            defects.append(
                {
                    "inspectionId": inspection_id,
                    "defectType": defect_type,
                    "confidence": confidence,
                    "boundingBox": bounding_box,
                    "severity": severity,
                    "detectedAt": datetime.now(timezone.utc),
                }
            )

        # =========================================================
        # 4. OVERALL SEVERITY
        # =========================================================

        if defects:
            overall_level = max(
                (d["severity"] for d in defects),
                key=lambda level: SEVERITY_ORDER.get(
                    level,
                    0,
                ),
            )
        else:
            overall_level = "minor"

        severity = {
            "score": (
                0
                if not defects
                else SEVERITY_ORDER[overall_level] * 25
            ),
            "level": overall_level,
            "explanation": (
                f"Overall severity is {overall_level} "
                f"based on {len(defects)} detected defect(s)."
            ),
        }

        # =========================================================
        # 5. RISK
        # =========================================================

        risk = calculate_risk(
            defects=defects,
            deterioration_status=inspection.get(
                "deteriorationStatus"
            ),
        )

        risk["explanation"] = risk_explanation(
            risk,
            len(defects),
        )

        # =========================================================
        # 6. PERSIST DEFECTS + SEVERITY + RISK
        # =========================================================

        model_version = "yolov8n-concrete-crack-v1"

        analyzed_at = await replace_analysis_for_inspection(
            inspection_id=inspection_id,
            defects=defects,
            severity=severity,
            risk=risk,
            model_version=model_version,
        )

        # =========================================================
        # 7. RETURN COMPLETE ANALYSIS
        # =========================================================

        return {
            "inspectionId": inspection_id,
            "analysisStatus": "completed",
            "defects": defects,
            "severity": severity,
            "risk": risk,
            "modelVersion": model_version,
            "analyzedAt": analyzed_at,
        }

    except FileNotFoundError as exc:
        raise HTTPException(
            status_code=404,
            detail=str(exc),
        ) from exc

    except Exception as exc:
        logger.exception(
            "Inspection analysis failed for %s",
            inspection_id,
        )

        raise HTTPException(
            status_code=500,
            detail=f"Inspection analysis failed: {exc}",
        ) from exc

    finally:
        if temp_path and os.path.exists(temp_path):
            os.unlink(temp_path)


# ============================================================
# GET SINGLE INSPECTION
# ============================================================
 main

@router.get(
    "/api/inspections/{inspection_id}",
    response_model=InspectionOut,
)
 feature/frontend-scaffold
async def get_inspection(
    inspection_id: str,
    current_user: dict = Depends(get_current_user),
):
    inspection = await get_inspection_by_id(inspection_id)

async def get_inspection_route(
    inspection_id: str,
    current_user: dict = Depends(get_current_user),
):
    inspection = await get_inspection_by_id(
        inspection_id
    )
main

    if inspection is None:
        raise HTTPException(
            status_code=404,
 feature/frontend-scaffold
            detail="Inspection not found.",
        )

    if str(inspection.get("userId", "")) != str(current_user["_id"]):
        raise HTTPException(
            status_code=404,
            detail="Inspection not found.",

            detail="Inspection not found",
 main
        )

    return _to_inspection_out(inspection)


 feature/frontend-scaffold

# ============================================================
# GET INSPECTIONS FOR ASSET
# ============================================================
 main
@router.get(
    "/api/assets/{asset_id}/inspections",
    response_model=list[InspectionOut],
)
 feature/frontend-scaffold
async def get_asset_inspections(
    asset_id: str,
    current_user: dict = Depends(get_current_user),
):
    inspections = await get_inspections_by_asset(asset_id)

    return [
        _to_inspection_out(inspection)
        for inspection in inspections
        if str(inspection.get("userId", ""))
        == str(current_user["_id"])
    ]


@router.patch(
    "/api/inspections/{inspection_id}",
    response_model=InspectionOut,
)
async def update_inspection_route(
    inspection_id: str,
    status: str | None = None,
    current_user: dict = Depends(get_current_user),
):
    inspection = await get_inspection_by_id(inspection_id)
async def list_inspections_for_asset_route(
    asset_id: str,
    current_user: dict = Depends(get_current_user),
):
    inspections = await get_inspections_by_asset(
        asset_id
    )

    return [
        _to_inspection_out(i)
        for i in inspections
    ]


# ============================================================
# IMAGE QUALITY CHECK
# ============================================================

@router.post(
    "/api/inspections/{inspection_id}/quality-check",
    response_model=InspectionOut,
)
async def quality_check_route(
    inspection_id: str,
    current_user: dict = Depends(get_current_user),
):
    inspection = await get_inspection_by_id(
        inspection_id
    )
main

    if inspection is None:
        raise HTTPException(
            status_code=404,
feature/frontend-scaffold
            detail="Inspection not found.",
        )

    if str(inspection.get("userId", "")) != str(current_user["_id"]):
        raise HTTPException(
            status_code=404,
            detail="Inspection not found.",
        )

    update_data = {}

    if status is not None:
        update_data["status"] = status

    if not update_data:
        return _to_inspection_out(inspection)

    updated = await update_inspection(
        inspection_id,
        update_data,
    )
            detail="Inspection not found",
        )

    quality_result = assess_image_quality(
        inspection["imageUrl"]
    )

    updated = await update_inspection(
        inspection_id,
        {
            "imageQuality": quality_result
        },
    )

    if updated is None:
        raise HTTPException(
            status_code=404,
            detail="Inspection not found",
        )

    return _to_inspection_out(updated)


# ============================================================
# RUN DEFECT ANALYSIS
# ============================================================

@router.post(
    "/api/inspections/{inspection_id}/analyze",
    response_model=AnalysisOut,
)
async def analyze_inspection(
    inspection_id: str,
    current_user: dict = Depends(get_current_user),
):
    # --------------------------------------------------------
    # 1. Get inspection
    # --------------------------------------------------------

    inspection = await get_inspection_by_id(
        inspection_id
    )

    if inspection is None:
        raise HTTPException(
            status_code=404,
            detail="Inspection not found.",
        )

    # --------------------------------------------------------
    # 2. OWNERSHIP CHECK
    # --------------------------------------------------------

    inspection_user_id = str(
        inspection.get("userId", "")
    )

    current_user_id = str(
        current_user["_id"]
    )

    if inspection_user_id != current_user_id:
        raise HTTPException(
            status_code=404,
            detail="Inspection not found.",
        )

    # --------------------------------------------------------
    # 3. Check uploaded image
    # --------------------------------------------------------

    if not inspection.get("imageUrl"):
        raise HTTPException(
            status_code=400,
            detail="Inspection has no uploaded image.",
        )

    try:

        # ----------------------------------------------------
        # 4. Run existing YOLO detection
        #
        # CHANGE run_defect_detection() to the function
        # already present in your Phase 6 YOLO service.
        #
        # It must return:
        #
        # defects
        # image_width
        # image_height
        # ----------------------------------------------------

        defects, image_width, image_height = (
            await run_defect_detection(
                inspection["imageUrl"]
            )
        )

        # ----------------------------------------------------
        # 5. Get image quality score
        # ----------------------------------------------------

        quality_score = (
            inspection.get("imageQuality") or {}
        ).get("score")

        # ----------------------------------------------------
        # 6. Calculate severity
        # ----------------------------------------------------

        severity = calculate_severity(
            defects,
            image_width,
            image_height,
            quality_score,
        ).as_dict()

        # ----------------------------------------------------
        # 7. Get asset
        # ----------------------------------------------------

        asset = await get_asset_by_id(
            inspection["assetId"]
        )

        # ----------------------------------------------------
        # 8. Calculate risk
        # ----------------------------------------------------

        risk = calculate_risk(
            severity_score=severity["score"],
            defect_count=len(defects),
            asset_criticality=(
                asset or {}
            ).get("criticality"),
            quality_score=quality_score,
        ).as_dict()

        # ----------------------------------------------------
        # 9. Persist analysis
        #
        # Old defects for ONLY this inspection are deleted
        # before the new results are inserted.
        # ----------------------------------------------------

        model_version = (
            "yolov8n-concrete-crack-v1"
        )

        analyzed_at = (
            await replace_analysis_for_inspection(
                inspection_id=inspection_id,
                defects=defects,
                severity=severity,
                risk=risk,
                model_version=model_version,
            )
        )

    except ValueError as exc:

        raise HTTPException(
            status_code=422,
            detail=str(exc),
        ) from exc

    except Exception as exc:

        logger.exception(
            "Analysis failed for inspection %s",
            inspection_id,
        )

        raise HTTPException(
            status_code=500,
            detail="Image analysis failed. Please retry.",
        ) from exc

    # --------------------------------------------------------
    # 10. Return analysis response
    # --------------------------------------------------------
 main

    return {
        "inspectionId": inspection_id,
        "analysisStatus": "completed",
        "defects": defects,
        "severity": severity,
        "risk": risk,
        "modelVersion": model_version,
        "analyzedAt": analyzed_at,
    }